# Enable mouse mode
set -g mouse on

# Start counting pane and window number at 1
set -g base-index 1
setw -g pane-base-index 1

# Vi-mode for buffer navigation
setw -g mode-keys vi

# Vi-style selection and yanking
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy -selection clipboard -i"
#bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy -selection clipboard -i"

# Fish as default
set-option -g default-shell /usr/bin/fish

# Enable focus-events
set-option -g focus-events on
